services:
  windmill_server:
    image: ${WM_IMAGE}
    pull_policy: always
    deploy:
      replicas: 0
    restart: unless-stopped
    expose:
      - 8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MODE=server
    volumes:
      - worker_logs:/tmp/windmill/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.windmill.rule=Host(`${BASE_URL}`) && PathPrefix(`/`)"
      - "traefik.http.services.windmill.loadbalancer.server.port=8000"

  windmill_worker:
    image: ${WM_IMAGE}
    pull_policy: always
    deploy:
      replicas: 0
      resources:
        limits:
          cpus: "1"
          memory: 2048M
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MODE=worker
      - WORKER_GROUP=default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - worker_dependency_cache:/tmp/windmill/cache
      - worker_logs:/tmp/windmill/logs

  windmill_worker_native:
    image: ${WM_IMAGE}
    pull_policy: always
    deploy:
      replicas: 0
      resources:
        limits:
          cpus: "0.1"
          memory: 128M
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MODE=worker
      - WORKER_GROUP=native
    volumes:
      - worker_logs:/tmp/windmill/logs

  windmill_indexer:
    image: ${WM_IMAGE}
    pull_policy: always
    deploy:
      replicas: 0
    restart: unless-stopped
    expose:
      - 8001
    environment:
      - PORT=8001
      - DATABASE_URL=${DATABASE_URL}
      - MODE=indexer
      - TANTIVY_REFRESH_INDEX_PERIOD__S=300
      - TANTIVY_DOC_COMMIT_MAX_BATCH_SIZE=100000
      - TANTIVY_SHOW_MEMORY_EVERY=10000
    volumes:
      - windmill_index:/tmp/windmill/search
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.indexer.rule=Host(`${BASE_URL}`) && PathPrefix(`/api/srch`)"
      - "traefik.http.services.indexer.loadbalancer.server.port=8001"

  lsp:
    image: ghcr.io/windmill-labs/windmill-lsp:latest
    pull_policy: always
    restart: unless-stopped
    expose:
      - 3001
    volumes:
      - lsp_cache:/root/.cache
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lsp.rule=Host(`${BASE_URL}`) && PathPrefix(`/ws`)"
      - "traefik.http.services.lsp.loadbalancer.server.port=3001"

  multiplayer:
    image: ghcr.io/windmill-labs/windmill-multiplayer:latest
    deploy:
      replicas: 0
    restart: unless-stopped
    expose:
      - 3002
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.multiplayer.rule=Host(`${BASE_URL}`) && PathPrefix(`/ws_mp`)"
      - "traefik.http.services.multiplayer.loadbalancer.server.port=3002"

volumes:
  worker_dependency_cache: null
  worker_logs: null
  windmill_index: null
  lsp_cache: null
